Bolg_App_Rails
AhmadiGu/Bolg_App_Rails pull request #10
Opened 2023-03-22 16:14 UTC by AhmadiGu

### Add device
*The following changes introduced:*

- Can register a new user.
- User logs in with a combination of email and password.
- Hashed password should be stored in the database.
- Ask for confirmation of email.
- Can reset password.

2023-03-22 20:52 UTC, Gambit142 requested changes
Hi @AhmadiGu @Tamunokuro 👋, 

Good job so far!

## Highlights
- All linters checks passed ✔️ 
- Used `devise` gem ✔️ 
- Pull request summary is descriptive ✔️ 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please, remember to tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-03-22 20:52 UTC, Gambit142 commented on app/controllers/application_controller.rb
> +  # end
- [ ] Kindly remove this commented code from this file. Removing such codes makes your work look clean. 👍 💻

2023-03-22 20:52 UTC, Gambit142 commented on app/controllers/user/confirmations_controller.rb
> +end
- [ ] You don't need this file because `devise` automatically configures authentication for all scenarios. So, all you have to do is plug and play. Kindly delete the following files that you created in the `app/controllers/users` directory:
- confirmations_controller.rb
- omniauth_callbacks_controller.rb
- passwords_controller.rb
- registrations_controller.rb
- sessions_controller.rb
- unlocks_controller.rb

2023-03-22 20:52 UTC, Gambit142 commented on config/environments/development.rb
> +  config.action_mailer.perform_deliveries = true
- [ ] Due to these blocks of code, I get an error when I try to signup or reset passwords

![image](https://user-images.githubusercontent.com/77106962/227030569-5b46f5b0-c2dd-4b39-a33c-1de074f7fb3d.png)

#### The way you have set the `smtp` settings is wrong and causes the error shown above. I would advise you to remove those blocks of code and leave these:

```ruby
config.action_mailer.default_url_options = { host: 'localhost', port: 3000 
  config.action_mailer.raise_delivery_errors = false
```

The reason why I recommended the last line of code is that you are currently not delivering confirmation messages. I have to get the link through the terminal for now. 👍 😎

2023-03-22 20:52 UTC, Gambit142 commented on db/migrate/20230322102425_add_confirmable_to_devise.rb
> +end
- [ ] Kindly delete this migration file. I get the error that the `confirmation_token` and all the other confirmation attributes have been set up already. Remember that `devise` automatically sets all features so you don't have to manually set it up. 👍 💻

2023-03-22 20:52 UTC, Gambit142 commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable, :confirmable
- [OPTIONAL] Great work setting up the `:confirmable` attribute here. However, when I try to **_signup_**, I noticed that your application doesn't display the confirmation page or give the information that users should check their email for the confirmation link. I have to manually get the link from the terminal to confirm and perform email confirmation. 

This is accessible to me as a developer but not as a user. As a user, I would not be able to access the confirmation link because I would be using the browser and not the terminal. This could frustrate users and eventually mean they would not be able to use your application. I would advise you to improve the user experience of your application by making it possible to display the page that directs users to check their mail for the confirmation link and also to deliver the mail with the confirmation link. You can read this [article](https://www.bogotobogo.com/RubyOnRails/RubyOnRails_Devise_Authentication_Sending_Confirmation_Email.php) to learn how to configure such. 👍 😃

2023-03-23 13:11 UTC, VICTOR-CHUKWU approved these changes
Hi @AhmadiGu , 
# STATUS: APPROVED! 🥇 💯 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- [ ] All linters passed
- [ ] used devise correctly

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-28 04:13 UTC, merged